### ISSUE TITLE
Bank holidays

### ISSUE THREAD

**Issue by Vict0rSch** [AntoineAugusti/vacances-scolaires-france#4]
Don't know if they're open sourced but you could include the bank holidays!

(1st of Jan. 1st + 8th of May, Ascension, Assomption, 11th of Nov., 25th of Dec.)

I know most of them are a fixed date but could be good to have it part if the package anyway

**Comment by AntoineAugusti** [comment]
@Vict0rSch Hello! Fortunately there is another package for this 👍 https://github.com/AntoineAugusti/jours-feries-france

**Comment by AntoineAugusti** [comment]
I've mentioned this package in the README https://github.com/AntoineAugusti/vacances-scolaires-france/pull/5

**Comment by Vict0rSch** [comment]
haha missed that sorry, you're the man
