### ISSUE TITLE
Les zones ont changées

### ISSUE THREAD

**Issue by Pouet78** [AntoineAugusti/vacances-scolaires-france#6]
lors du passage de 22 à 13 régions, les répartitions des différentes académies dans chaque zone ont changées. Il serait intéressant d'avoir cette notion.

**Comment by AntoineAugusti** [comment]
Merci de votre vigilance ! Je suis étonné, ce n'était pas indiqué sur le site des archives du calendrier scolaire : http://www.education.gouv.fr/cid197/les-archives-calendrier-scolaire-partir-1960.html.

La modification des zones est renseignée dans le README.
