### ISSUE TITLE
PyPa python package does not include data

### ISSUE THREAD

**Issue by opus-42** [AntoineAugusti/vacances-scolaires-france#7]
The Pypa python package installed using `pip install vacances-scolaires-france` does not seems to include package data.

Steps to reproduce missing data error :

- Download python package using pip
- Running the following commands (outside local package folder) should produce a FileNotFound error.
```
import datetime

import vacances_scolaires_france

v = vacances_scolaires_france.SchoolHolidayDates()
```

I think there is a conflict between include_package_data=True and package_date which cause the command `python3 -m setup sdist` to look for a MANIFEST.in and thus ignore package_data.

I will submit a pull request.

**Comment by opus-42** [comment]
here is the pull request #8

**Comment by AntoineAugusti** [comment]
I just released a bugfix version https://github.com/AntoineAugusti/vacances-scolaires-france/commit/e443e037356894c00266b3e8d054092486818e7b. Can you try again and confirm the fix?

**Comment by opus-42** [comment]
It's working now with version 0.6.1.
Thanks

**Comment by AntoineAugusti** [comment]
Awesome
